export const elements = [
  ['H','氢'],['He','氦'],['Li','锂'],['Be','铍'],['B','硼'],['C','碳'],['N','氮'],['O','氧'],['F','氟'],['Ne','氖'],['Na','钠'],['Mg','镁'],['Al','铝'],['Si','硅'],['P','磷'],['S','硫'],['Cl','氯'],['Ar','氩'],['K','钾'],['Ca','钙'],['Sc','钪'],['Ti','钛'],['V','钒'],['Cr','铬'],['Mn','锰'],['Fe','铁'],['Co','钴'],['Ni','镍'],['Cu','铜'],['Zn','锌'],['Ga','镓'],['Ge','锗'],['As','砷'],['Se','硒'],['Br','溴'],['Kr','氪'],['Rb','铷'],['Sr','锶'],['Y','钇'],['Zr','锆'],['Nb','铌'],['Mo','钼'],['Tc','锝'],['Ru','钌'],['Rh','铑'],['Pd','钯'],['Ag','银'],['Cd','镉'],['In','铟'],['Sn','锡'],['Sb','锑'],['Te','碲'],['I','碘'],['Xe','氙'],['Cs','铯'],['Ba','钡'],['La','镧'],['Ce','铈'],['Pr','镨'],['Nd','钕'],['Pm','钷'],['Sm','钐'],['Eu','铕'],['Gd','钆'],['Tb','铽'],['Dy','镝'],['Ho','钬'],['Er','铒'],['Tm','铥'],['Yb','镱'],['Lu','镥'],['Hf','铪'],['Ta','钽'],['W','钨'],['Re','铼'],['Os','锇'],['Ir','铱'],['Pt','铂'],['Au','金'],['Hg','汞'],['Tl','铊'],['Pb','铅'],['Bi','铋'],['Po','钋'],['At','砹'],['Rn','氡'],['Fr','钫'],['Ra','镭'],['Ac','锕'],['Th','钍'],['Pa','镤'],['U','铀'],['Np','镎'],['Pu','钚'],['Am','镅'],['Cm','锔'],['Bk','锫'],['Cf','锎'],['Es','锿'],['Fm','镄'],['Md','钔'],['No','锘'],['Lr','铹'],['Rf','𬬻'],['Db','𬭊'],['Sg','𬭳'],['Bh','𬭛'],['Hs','𬭶'],['Mt','鿏'],['Ds','𫟼'],['Rg','𬬭'],['Cn','鿔'],['Nh','鉨'],['Fl','鈇'],['Mc','镆'],['Lv','鉝'],['Ts','鿬'],['Og','鿫']
].map(([symbol, name], index) => ({ symbol, name, atomic: index + 1, category: index < 2 ? '主族元素' : index > 88 ? '锕系 / 合成元素' : '原子轨道' }));

export const periodicRows = [
  ['H',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'He'],
  ['Li','Be',null,null,null,null,null,null,null,null,null,null,'B','C','N','O','F','Ne'],
  ['Na','Mg',null,null,null,null,null,null,null,null,null,null,'Al','Si','P','S','Cl','Ar'],
  ['K','Ca','Sc','Ti','V','Cr','Mn','Fe','Co','Ni','Cu','Zn','Ga','Ge','As','Se','Br','Kr'],
  ['Rb','Sr','Y','Zr','Nb','Mo','Tc','Ru','Rh','Pd','Ag','Cd','In','Sn','Sb','Te','I','Xe'],
  ['Cs','Ba','La','Hf','Ta','W','Re','Os','Ir','Pt','Au','Hg','Tl','Pb','Bi','Po','At','Rn'],
  ['Fr','Ra','Ac','Rf','Db','Sg','Bh','Hs','Mt','Ds','Rg','Cn','Nh','Fl','Mc','Lv','Ts','Og'],
  [null,null,null,'Ce','Pr','Nd','Pm','Sm','Eu','Gd','Tb','Dy','Ho','Er','Tm','Yb','Lu',null],
  [null,null,null,'Th','Pa','U','Np','Pu','Am','Cm','Bk','Cf','Es','Fm','Md','No','Lr',null]
];

const planarRing = (symbols,cx=0,cy=0,radius=1.1,phase=0,zWave=0) => symbols.map((symbol,index)=>({
  symbol,x:cx+radius*Math.cos(phase+index*Math.PI*2/symbols.length),y:cy+radius*Math.sin(phase+index*Math.PI*2/symbols.length),z:index%2?zWave:-zWave,
}));

export const molecules = [
  { id: 'water', formula: 'H₂O', name: '水', geometry: '折线型', description: '氧原子的孤对电子使水分子呈约 104.5° 的弯曲结构。', atoms: [{symbol:'O',x:0,y:0,z:0},{symbol:'H',x:-1.25,y:.72,z:0},{symbol:'H',x:1.25,y:.72,z:0}] },
  { id: 'co2', formula: 'CO₂', name: '二氧化碳', geometry: '线性', description: '中心碳与两个氧原子形成对称的双键电子密度。', atoms: [{symbol:'C',x:0,y:0,z:0},{symbol:'O',x:-1.5,y:0,z:0},{symbol:'O',x:1.5,y:0,z:0}] },
  { id: 'methane', formula: 'CH₄', name: '甲烷', geometry: '正四面体', description: '四个 C–H 键指向正四面体的顶点。', atoms: [{symbol:'C',x:0,y:0,z:0},{symbol:'H',x:1,y:1,z:1},{symbol:'H',x:-1,y:-1,z:1},{symbol:'H',x:-1,y:1,z:-1},{symbol:'H',x:1,y:-1,z:-1}] },
  { id: 'ammonia', formula: 'NH₃', name: '氨', geometry: '三角锥', description: '氮原子的孤对电子塑造三角锥分子构型。', atoms: [{symbol:'N',x:0,y:0,z:0},{symbol:'H',x:1.1,y:.5,z:.65},{symbol:'H',x:-1.1,y:.5,z:.65},{symbol:'H',x:0,y:.5,z:-1.1}] },
  { id: 'oxygen', formula: 'O₂', name: '氧气', geometry: '线性', description: '同核双原子的 π 轨道展示键合和反键合电子密度。', atoms: [{symbol:'O',x:-.9,y:0,z:0},{symbol:'O',x:.9,y:0,z:0}] },
  { id: 'nitrogen', formula: 'N₂', name: '氮气', geometry: '线性', description: '强三键使氮气在常温下具有很高稳定性。', atoms: [{symbol:'N',x:-.9,y:0,z:0},{symbol:'N',x:.9,y:0,z:0}] },
  { id: 'benzene', formula: 'C₆H₆', name: '苯', geometry: '平面六角形', description: '离域 π 电子云包覆在碳环上下方。', atoms: Array.from({length:6},(_,i)=>({symbol:'C',x:1.35*Math.cos(i*Math.PI/3),y:1.35*Math.sin(i*Math.PI/3),z:0})) },
  { id: 'ethanol', formula: 'C₂H₆O', name: '乙醇', geometry: '链状', description: '羟基氧的高电子密度决定其极性与氢键性质。', atoms: [{symbol:'C',x:-1.5,y:0,z:0},{symbol:'C',x:0,y:0,z:0},{symbol:'O',x:1.35,y:.25,z:0},{symbol:'H',x:2.1,y:.9,z:0}] },
  { id: 'sulfuric', formula: 'H₂SO₄', name: '硫酸', geometry: '四面体核心', description: '硫氧四面体核心与极性 O–H 键共同构成酸性结构。', atoms: [{symbol:'S',x:0,y:0,z:0},{symbol:'O',x:1.15,y:1.15,z:1.15},{symbol:'O',x:-1.15,y:-1.15,z:1.15},{symbol:'O',x:-1.15,y:1.15,z:-1.15},{symbol:'O',x:1.15,y:-1.15,z:-1.15}] },
  { id: 'sodiumchloride', formula: 'NaCl', name: '氯化钠', geometry: '离子对', description: '离子键可视为电子密度从钠向氯的显著偏移。', atoms: [{symbol:'Na',x:-1.1,y:0,z:0},{symbol:'Cl',x:1.1,y:0,z:0}] },
  { id: 'ozone', formula: 'O₃', name: '臭氧', geometry: '折线型', description: '共振使 π 电子在三个氧原子之间离域。', atoms: [{symbol:'O',x:0,y:0,z:0},{symbol:'O',x:-1.2,y:.75,z:0},{symbol:'O',x:1.2,y:.75,z:0}] },
  { id: 'glucose', formula: 'C₆H₁₂O₆', name: '葡萄糖', geometry: '环状', description: '碳、氧骨架形成富含羟基的环状分子网络。', atoms: Array.from({length:6},(_,i)=>({symbol:i===0?'O':'C',x:1.5*Math.cos(i*Math.PI/3),y:1.5*Math.sin(i*Math.PI/3),z:i%2?.35:-.35})) },
  { id: 'peroxide', formula: 'H₂O₂', name: '过氧化氢', geometry: '非平面链状', description: 'O–O 单键连接两个羟基，分子具有扭转构型。', atoms: [{symbol:'O',x:-.65,y:0,z:0},{symbol:'O',x:.65,y:0,z:0},{symbol:'H',x:-1.25,y:.65,z:.35},{symbol:'H',x:1.25,y:-.65,z:.35}] },
  { id: 'carbonmonoxide', formula: 'CO', name: '一氧化碳', geometry: '线性', description: '碳氧之间形成短而强的多重键。', atoms: [{symbol:'C',x:-.62,y:0,z:0},{symbol:'O',x:.62,y:0,z:0}] },
  { id: 'hydrogenchloride', formula: 'HCl', name: '氯化氢', geometry: '线性', description: '电子密度明显偏向电负性较强的氯原子。', atoms: [{symbol:'H',x:-.85,y:0,z:0},{symbol:'Cl',x:.85,y:0,z:0}] },
  { id: 'sulfurdioxide', formula: 'SO₂', name: '二氧化硫', geometry: '折线型', description: '硫中心的孤对电子使两个 S–O 键形成弯曲结构。', atoms: [{symbol:'S',x:0,y:-.25,z:0},{symbol:'O',x:-1.15,y:.65,z:0},{symbol:'O',x:1.15,y:.65,z:0}] },
  { id: 'nitrogendioxide', formula: 'NO₂', name: '二氧化氮', geometry: '折线型', description: '含有未成对电子的弯曲自由基分子。', atoms: [{symbol:'N',x:0,y:-.2,z:0},{symbol:'O',x:-1.05,y:.65,z:0},{symbol:'O',x:1.05,y:.65,z:0}] },
  { id: 'nitricacid', formula: 'HNO₃', name: '硝酸', geometry: '平面型', description: '硝酸根骨架上的电子密度具有明显离域特征。', atoms: [{symbol:'N',x:0,y:0,z:0},{symbol:'O',x:-1.1,y:.55,z:0},{symbol:'O',x:1.1,y:.55,z:0},{symbol:'O',x:0,y:-1.2,z:0},{symbol:'H',x:-1.75,y:1.05,z:0}] },
  { id: 'phosphoricacid', formula: 'H₃PO₄', name: '磷酸', geometry: '四面体核心', description: '磷氧四面体带有三个可形成氢键的羟基。', atoms: [{symbol:'P',x:0,y:0,z:0},{symbol:'O',x:1,y:1,z:1},{symbol:'O',x:-1,y:-1,z:1},{symbol:'O',x:-1,y:1,z:-1},{symbol:'O',x:1,y:-1,z:-1},{symbol:'H',x:1.65,y:1.35,z:1.25},{symbol:'H',x:-1.65,y:-1.35,z:1.25},{symbol:'H',x:-1.65,y:1.35,z:-1.25}] },
  { id: 'formaldehyde', formula: 'CH₂O', name: '甲醛', geometry: '平面三角形', description: '羰基使电子密度显著偏向氧端。', atoms: [{symbol:'C',x:0,y:0,z:0},{symbol:'O',x:1.25,y:0,z:0},{symbol:'H',x:-.75,y:.9,z:0},{symbol:'H',x:-.75,y:-.9,z:0}] },
  { id: 'acetylene', formula: 'C₂H₂', name: '乙炔', geometry: '线性', description: '碳碳三键形成轴对称的高密度键区。', atoms: [{symbol:'H',x:-2.05,y:0,z:0},{symbol:'C',x:-.68,y:0,z:0},{symbol:'C',x:.68,y:0,z:0},{symbol:'H',x:2.05,y:0,z:0}] },
  { id: 'ethylene', formula: 'C₂H₄', name: '乙烯', geometry: '平面型', description: '碳碳双键包含位于分子平面上下的 π 电子密度。', atoms: [{symbol:'C',x:-.68,y:0,z:0},{symbol:'C',x:.68,y:0,z:0},{symbol:'H',x:-1.35,y:.9,z:0},{symbol:'H',x:-1.35,y:-.9,z:0},{symbol:'H',x:1.35,y:.9,z:0},{symbol:'H',x:1.35,y:-.9,z:0}] },
  { id: 'propane', formula: 'C₃H₈', name: '丙烷', geometry: '锯齿链状', description: '三个碳形成饱和链状骨架。', atoms: [{symbol:'C',x:-1.3,y:.25,z:0},{symbol:'C',x:0,y:-.25,z:0},{symbol:'C',x:1.3,y:.25,z:0},{symbol:'H',x:-1.8,y:1,z:.45},{symbol:'H',x:-1.8,y:-.45,z:.65},{symbol:'H',x:-1.35,y:.35,z:-1},{symbol:'H',x:0,y:-1.15,z:.7},{symbol:'H',x:0,y:-.45,z:-1},{symbol:'H',x:1.8,y:1,z:.45},{symbol:'H',x:1.8,y:-.45,z:.65},{symbol:'H',x:1.35,y:.35,z:-1}] },
  { id: 'aceticacid', formula: 'C₂H₄O₂', name: '乙酸', geometry: '羧基平面', description: '羧基内的电子离域与极性决定其酸性。', atoms: [{symbol:'C',x:-.8,y:0,z:0},{symbol:'C',x:.55,y:0,z:0},{symbol:'O',x:1.3,y:.9,z:0},{symbol:'O',x:1.3,y:-.9,z:0},{symbol:'H',x:-1.35,y:.8,z:.65},{symbol:'H',x:-1.35,y:.2,z:-.9},{symbol:'H',x:-1.35,y:-.8,z:.4},{symbol:'H',x:2.05,y:-1.1,z:0}] },
  { id: 'urea', formula: 'CH₄N₂O', name: '尿素', geometry: '近似平面', description: '羰基与两个氨基之间存在共振离域。', atoms: [{symbol:'C',x:0,y:0,z:0},{symbol:'O',x:0,y:1.25,z:0},{symbol:'N',x:-1.15,y:-.55,z:0},{symbol:'N',x:1.15,y:-.55,z:0},{symbol:'H',x:-1.85,y:0,z:0},{symbol:'H',x:-1.35,y:-1.4,z:0},{symbol:'H',x:1.85,y:0,z:0},{symbol:'H',x:1.35,y:-1.4,z:0}] },
  { id: 'acetone', formula: 'C₃H₆O', name: '丙酮', geometry: '羰基平面', description: '中心羰基连接两个甲基，氧端具有较高电子密度。', atoms: [{symbol:'C',x:0,y:0,z:0},{symbol:'O',x:0,y:1.3,z:0},{symbol:'C',x:-1.35,y:-.35,z:0},{symbol:'C',x:1.35,y:-.35,z:0},{symbol:'H',x:-1.8,y:.2,z:.8},{symbol:'H',x:-1.8,y:.2,z:-.8},{symbol:'H',x:-1.55,y:-1.3,z:0},{symbol:'H',x:1.8,y:.2,z:.8},{symbol:'H',x:1.8,y:.2,z:-.8},{symbol:'H',x:1.55,y:-1.3,z:0}] },
  { id: 'bicarbonate', formula: 'NaHCO₃', name: '碳酸氢钠', geometry: '离子复合体', description: '钠离子与平面碳酸氢根共同构成离子化合物。', atoms: [{symbol:'Na',x:-2,y:0,z:0},{symbol:'C',x:.2,y:0,z:0},{symbol:'O',x:1.35,y:0,z:0},{symbol:'O',x:-.25,y:1.15,z:0},{symbol:'O',x:-.25,y:-1.15,z:0},{symbol:'H',x:-.8,y:-1.75,z:0}] },
  { id:'caffeine', formula:'C₈H₁₀N₄O₂', name:'咖啡因', geometry:'稠合杂环', description:'两个稠合含氮环和羰基形成高度离域的共轭轨道。', atoms:[{symbol:'N',x:-.9,y:.55,z:0},{symbol:'C',x:0,y:1.05,z:0},{symbol:'N',x:.9,y:.55,z:0},{symbol:'C',x:.9,y:-.5,z:0},{symbol:'C',x:0,y:-1,z:0},{symbol:'N',x:-.9,y:-.5,z:0},{symbol:'N',x:1.75,y:1,z:0},{symbol:'C',x:2.45,y:.25,z:0},{symbol:'C',x:1.75,y:-.75,z:0},{symbol:'O',x:0,y:2.15,z:0},{symbol:'O',x:0,y:-2.1,z:0},{symbol:'C',x:-2,y:.95,z:.2},{symbol:'C',x:-2,y:-.85,z:-.2},{symbol:'C',x:2.05,y:2.1,z:.2}], bonds:[[0,1],[1,2],[2,3],[3,4],[4,5],[5,0],[2,6],[6,7,2],[7,8],[8,3],[1,9,2],[4,10,2],[0,11],[5,12],[6,13]] },
  { id:'aspirin', formula:'C₉H₈O₄', name:'阿司匹林', geometry:'芳香酯', description:'苯环、羧基和乙酰氧基构成相互耦合的 π 电子区域。', atoms:[...planarRing(Array(6).fill('C')), {symbol:'C',x:2.25,y:0,z:0},{symbol:'O',x:3.15,y:.55,z:0},{symbol:'O',x:3.15,y:-.55,z:0},{symbol:'O',x:-1.1,y:1.9,z:0},{symbol:'C',x:-.55,y:2.85,z:0},{symbol:'O',x:.5,y:3.25,z:0},{symbol:'C',x:-1.55,y:3.55,z:.2}], bonds:[[0,1,1.5],[1,2,1.5],[2,3,1.5],[3,4,1.5],[4,5,1.5],[5,0,1.5],[0,6],[6,7,2],[6,8],[2,9],[9,10],[10,11,2],[10,12]] },
  { id:'acetaminophen', formula:'C₈H₉NO₂', name:'对乙酰氨基酚', geometry:'共轭平面', description:'芳香环与酰胺基通过共轭共享电子密度。', atoms:[...planarRing(Array(6).fill('C')), {symbol:'O',x:2.2,y:0,z:0},{symbol:'N',x:-2.2,y:0,z:0},{symbol:'C',x:-3.25,y:0,z:0},{symbol:'O',x:-3.85,y:.95,z:0},{symbol:'C',x:-3.85,y:-.95,z:.2}], bonds:[[0,1,1.5],[1,2,1.5],[2,3,1.5],[3,4,1.5],[4,5,1.5],[5,0,1.5],[0,6],[3,7],[7,8],[8,9,2],[8,10]] },
  { id:'dopamine', formula:'C₈H₁₁NO₂', name:'多巴胺', geometry:'儿茶酚侧链', description:'儿茶酚芳环连接柔性的乙胺侧链，氧端具有较高电子密度。', atoms:[...planarRing(Array(6).fill('C')), {symbol:'O',x:1.1,y:1.9,z:0},{symbol:'O',x:-1.1,y:1.9,z:0},{symbol:'C',x:-1.1,y:-1.9,z:.2},{symbol:'C',x:-.4,y:-2.85,z:-.2},{symbol:'N',x:.65,y:-3.2,z:0}], bonds:[[0,1,1.5],[1,2,1.5],[2,3,1.5],[3,4,1.5],[4,5,1.5],[5,0,1.5],[1,6],[2,7],[4,8],[8,9],[9,10]] },
  { id:'adenine', formula:'C₅H₅N₅', name:'腺嘌呤', geometry:'稠合嘌呤环', description:'嘌呤骨架的 π 电子在两个稠合杂环中离域。', atoms:[{symbol:'N',x:-.9,y:.55,z:0},{symbol:'C',x:0,y:1.05,z:0},{symbol:'N',x:.9,y:.55,z:0},{symbol:'C',x:.9,y:-.5,z:0},{symbol:'C',x:0,y:-1,z:0},{symbol:'C',x:-.9,y:-.5,z:0},{symbol:'N',x:1.75,y:1,z:0},{symbol:'C',x:2.45,y:.25,z:0},{symbol:'N',x:1.75,y:-.75,z:0},{symbol:'N',x:0,y:2.15,z:0}], bonds:[[0,1,1.5],[1,2,1.5],[2,3,1.5],[3,4,1.5],[4,5,1.5],[5,0,1.5],[2,6],[6,7,1.5],[7,8,1.5],[8,3],[1,9]] },
  { id:'uracil', formula:'C₄H₄N₂O₂', name:'尿嘧啶', geometry:'嘧啶二酮环', description:'含氮六元环与两个羰基形成共轭 π 轨道。', atoms:[...planarRing(['N','C','N','C','C','C']),{symbol:'O',x:.55,y:1.95,z:0},{symbol:'O',x:-.55,y:-1.95,z:0}], bonds:[[0,1,1.5],[1,2,1.5],[2,3,1.5],[3,4,1.5],[4,5,1.5],[5,0,1.5],[1,6,2],[4,7,2]] },
  { id:'glycine', formula:'C₂H₅NO₂', name:'甘氨酸', geometry:'两性离子骨架', description:'氨基与羧基分布在中心碳两侧，羧基电子密度明显离域。', atoms:[{symbol:'C',x:-.7,y:0,z:0},{symbol:'C',x:.65,y:0,z:0},{symbol:'N',x:-1.75,y:.45,z:.2},{symbol:'O',x:1.4,y:.9,z:0},{symbol:'O',x:1.4,y:-.9,z:0}], bonds:[[0,1],[0,2],[1,3,1.5],[1,4,1.5]] },
  { id:'nicotine', formula:'C₁₀H₁₄N₂', name:'尼古丁', geometry:'双含氮环', description:'吡啶芳香环与饱和含氮五元环通过单键连接。', atoms:[...planarRing(['C','C','N','C','C','C'],-1.55,0,.85),...planarRing(['N','C','C','C','C'],1.55,0,.82,Math.PI/5,.18),{symbol:'C',x:1.9,y:1.8,z:.25}], bonds:[[0,1,1.5],[1,2,1.5],[2,3,1.5],[3,4,1.5],[4,5,1.5],[5,0,1.5],[6,7],[7,8],[8,9],[9,10],[10,6],[0,9],[6,11]] },
  { id:'sucrose', formula:'C₁₂H₂₂O₁₁', name:'蔗糖', geometry:'双环糖苷', description:'两个含氧糖环由糖苷键连接，并带有多个富电子羟基氧。', atoms:[...planarRing(['C','C','O','C','C','C'],-1.8,0,.9,0,.1),...planarRing(['C','C','O','C','C','C'],1.8,0,.9,0,.1),{symbol:'O',x:0,y:0,z:0},{symbol:'C',x:-2.7,y:-1.65,z:.2},{symbol:'C',x:2.7,y:1.65,z:-.2},{symbol:'O',x:-1,y:1.75,z:0},{symbol:'O',x:-3.75,y:0,z:0},{symbol:'O',x:-3.2,y:-.95,z:.2},{symbol:'O',x:-1,y:-1.75,z:0},{symbol:'O',x:3.75,y:0,z:0},{symbol:'O',x:3.2,y:.95,z:-.2},{symbol:'O',x:1,y:-1.75,z:0},{symbol:'O',x:2.8,y:-1.65,z:.2}], bonds:[[0,1],[1,2],[2,3],[3,4],[4,5],[5,0],[6,7],[7,8],[8,9],[9,10],[10,11],[11,6],[0,12],[12,9],[4,13],[7,14],[1,15],[3,16],[4,17],[5,18],[6,19],[7,20],[10,21],[11,22]] }
];
